# .readthedocs.yml for MkDocs
version: 2

build:
  tools:
    python: "3.10"
  os: ubuntu-22.04

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
